/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.callcenter.helper;

import com.callcenter.database.PrintProcesses;
import com.callcenter.database.ProjectProcesses;
import com.callcenter.database.WorkingProcesses;
import com.callcenter.entity.Employee;
import com.callcenter.entity.Project;
import com.callcenter.entity.SubProject;
import com.callcenter.entity.Working;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowFilter;
import javax.swing.RowFilter.ComparisonType;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author burakatlay
 */
public class Print extends javax.swing.JPanel {
    
    private DefaultTableModel modelProjectView;
    private Object[] dataProjectview;
    private SubProject subProject = new SubProject(0, "");
    private Employee employee = new Employee(3, "", "", "", "", "", "");
    private Working working = new Working();

    /**
     * Creates new form Print
     */
    public Print() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableWorking = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 330));
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Month : ");

        jLabel2.setText("Year : ");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Project : ");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Project" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        TableWorking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "WorkingId", "Project Name", "Sub Project Name", "Call Count", "Bonus", "Total", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TableWorking);
        if (TableWorking.getColumnModel().getColumnCount() > 0) {
            TableWorking.getColumnModel().getColumn(0).setMinWidth(0);
            TableWorking.getColumnModel().getColumn(0).setPreferredWidth(0);
            TableWorking.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jButton1.setText("Print");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 135, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        
        try {
            this.workingViewAddTable();
            this.projectsGet();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Print.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Print.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formAncestorAdded

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        
        this.filter();
        
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        this.filter();
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        
        this.filter();
        
    }//GEN-LAST:event_jComboBox2ActionPerformed


    private void workingViewAddTable() throws ClassNotFoundException, SQLException {
        PrintProcesses printProcesses = new PrintProcesses();
        int i = TableWorking.getRowCount();

        modelProjectView = (DefaultTableModel) TableWorking.getModel();
        for (int j = 0; j < i; j++) {
            modelProjectView.removeRow(0);
        }
        dataProjectview = new Object[7];
        for (Working working : printProcesses.workingWiev()) {
            double total = 0;
            total = (working.getSubProject().getPrice() * working.getCount()) + working.getBonus();
            dataProjectview[0] = working.getWorkingId();
            dataProjectview[1] = working.getSubProject().getProjectName();
            dataProjectview[2] = working.getSubProject().getSubProjectName();
            dataProjectview[3] = working.getCount();
            dataProjectview[4] = working.getBonus();
            dataProjectview[5] = total;
            dataProjectview[6] = working.getDate();

            modelProjectView.addRow(dataProjectview);

        }
        TableRowSorter tableRowSorter = new TableRowSorter(modelProjectView);
        TableWorking.setRowSorter(tableRowSorter);
    }
    
    private void projectsGet() throws ClassNotFoundException, SQLException{
        ProjectProcesses projectProcesses = new ProjectProcesses();
        for (Project project : projectProcesses.getProjectList()) {
            jComboBox3.addItem(project.getProjectName());
        }
    }
    
    private void filter(){
        
        int year = Integer.valueOf(jComboBox2.getItemAt(jComboBox2.getSelectedIndex()));
        int month = Integer.valueOf(jComboBox1.getItemAt(jComboBox1.getSelectedIndex()));
        
        java.sql.Date[] list = new java.sql.Date[2];
        WorkingProcesses workingProcesses = new WorkingProcesses();
        
        list = workingProcesses.firstAndLastDay(year, month);
        
        modelProjectView =  (DefaultTableModel) TableWorking.getModel();
        TableRowSorter<DefaultTableModel> tableRowSorter = new TableRowSorter<DefaultTableModel>(modelProjectView);
        TableWorking.setRowSorter(tableRowSorter);
        
        String query = jComboBox3.getItemAt(jComboBox3.getSelectedIndex());
        if (query=="All Project") {
            query = "";
        }
        
        ArrayList<RowFilter<Object,Object>> filters = new ArrayList<RowFilter<Object,Object>>(2);
        filters.add( RowFilter.dateFilter(ComparisonType.AFTER, list[0]) );
        filters.add( RowFilter.dateFilter(ComparisonType.BEFORE, list[1]) );
        filters.add( RowFilter.regexFilter(query) );
        tableRowSorter.setRowFilter(RowFilter.andFilter(filters));
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableWorking;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
