/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.callcenter.frame;

import com.callcenter.entity.Employee;
import com.callcenter.library.database.DatabaseManagement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author burakatlay
 */
public class LoginGUI extends javax.swing.JFrame {

    int xMause, yMause;
    /**
     * Creates new form LoginGUI
     */
    public LoginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        MiniBtn = new javax.swing.JLabel();
        CloseBtn = new javax.swing.JLabel();
        Description = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        userPassword = new javax.swing.JPasswordField();
        LoginBtn = new javax.swing.JLabel();
        TopBar = new javax.swing.JLabel();
        MainBackground = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MiniBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MiniBtnMouseClicked(evt);
            }
        });
        getContentPane().add(MiniBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 30, 40));

        CloseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseBtnMouseClicked(evt);
            }
        });
        getContentPane().add(CloseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 40, 40));

        Description.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        Description.setForeground(new java.awt.Color(37, 77, 88));
        getContentPane().add(Description, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 300, 30));

        userName.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        userName.setForeground(new java.awt.Color(37, 77, 88));
        userName.setBorder(null);
        userName.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                userNameMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                userNameMouseMoved(evt);
            }
        });
        userName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userNameMouseExited(evt);
            }
        });
        getContentPane().add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 250, 38));

        userPassword.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        userPassword.setForeground(new java.awt.Color(37, 77, 88));
        userPassword.setBorder(null);
        userPassword.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                userPasswordMouseMoved(evt);
            }
        });
        userPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userPasswordMouseExited(evt);
            }
        });
        getContentPane().add(userPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 123, 250, 38));

        LoginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/callcenter/image/LButton1.png"))); // NOI18N
        LoginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginBtnMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LoginBtnMouseReleased(evt);
            }
        });
        getContentPane().add(LoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 300, 40));

        TopBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/callcenter/image/loginTopBar.png"))); // NOI18N
        TopBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TopBarMouseDragged(evt);
            }
        });
        TopBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TopBarMousePressed(evt);
            }
        });
        getContentPane().add(TopBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        MainBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/callcenter/image/mainBackground.png"))); // NOI18N
        MainBackground.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MainBackgroundMouseExited(evt);
            }
        });
        getContentPane().add(MainBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseBtnMouseClicked

    private void MiniBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiniBtnMouseClicked
        this.setState(LoginGUI.ICONIFIED);
    }//GEN-LAST:event_MiniBtnMouseClicked

    private void TopBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TopBarMousePressed
        xMause = evt.getX();
        yMause = evt.getY();
    }//GEN-LAST:event_TopBarMousePressed

    private void TopBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TopBarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMause, y - yMause);
    }//GEN-LAST:event_TopBarMouseDragged

    private void LoginBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBtnMouseEntered
        ImageIcon img = new ImageIcon(getClass().getResource("../image/LButton2.png"));
        LoginBtn.setIcon(img);
    }//GEN-LAST:event_LoginBtnMouseEntered

    private void MainBackgroundMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainBackgroundMouseExited
        
    }//GEN-LAST:event_MainBackgroundMouseExited

    private void LoginBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBtnMouseReleased
        ImageIcon img = new ImageIcon(getClass().getResource("../image/LButton2.png"));
        LoginBtn.setIcon(img);
    }//GEN-LAST:event_LoginBtnMouseReleased

    private void userNameMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNameMouseMoved
        Description.setText("Enter your user name");
    }//GEN-LAST:event_userNameMouseMoved

    private void userNameMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNameMouseDragged
        
    }//GEN-LAST:event_userNameMouseDragged

    private void userNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNameMouseExited
        Description.setText("");
    }//GEN-LAST:event_userNameMouseExited

    private void LoginBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBtnMouseExited
        ImageIcon img = new ImageIcon(getClass().getResource("../image/LButton1.png"));
        LoginBtn.setIcon(img);
    }//GEN-LAST:event_LoginBtnMouseExited

    private void userPasswordMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userPasswordMouseMoved
        Description.setText("Enter your password");
    }//GEN-LAST:event_userPasswordMouseMoved

    private void userPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userPasswordMouseExited
        Description.setText("");
    }//GEN-LAST:event_userPasswordMouseExited

    private void LoginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBtnMouseClicked
        String userName1 = this.userName.getText();
        String userPassword1 = this.userPassword.getText();
        
        DatabaseManagement controlUser = new DatabaseManagement();
        Employee employee = null;
        try {
            employee = controlUser.loginUser(userName1, userPassword1);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(LoginGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
//        dispose();
//        new LoginGUI().setVisible(true);
        if (employee!=null) {
            Description.setText("Kayıt var");
            
//            System.out.println(employee.getEmployeeId() + " " + employee.getEmployeeName()
//            + " " + employee.getEmployeeSurname()+ " " + employee.getEmployeePhoto()
//            + " " + employee.getEmployeePassword()+ " " + employee.getEmployeeEmail()
//            + " " + employee.getEmployeeNickName());
        } else {
            Description.setText("User Not Found!");
        }

    }//GEN-LAST:event_LoginBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CloseBtn;
    private javax.swing.JLabel Description;
    private javax.swing.JLabel LoginBtn;
    private javax.swing.JLabel MainBackground;
    private javax.swing.JLabel MiniBtn;
    private javax.swing.JLabel TopBar;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField userName;
    private javax.swing.JPasswordField userPassword;
    // End of variables declaration//GEN-END:variables
}
