/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.callcenter.frame;

import com.callcenter.entity.Employee;
import com.callcenter.database.EmployeeProcesses;
import com.callcenter.database.ProjectProcesses;
import com.callcenter.database.SubProjectProcesses;
import com.callcenter.database.WorkingProcesses;
import com.callcenter.entity.Project;
import com.callcenter.entity.SubProject;
import com.callcenter.helper.Helper;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author burakatlay
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     *
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     */
    private DefaultTableModel projectModel, subProjectModel = null;
    private Object[] projectData, subProjectData = null;
    private int idProject;
    private int idSubProject;
    private static Project firstProject = null;
    private Project project = null;
    private SubProject subProject = null;

    public MainGUI() {

        initComponents();
        

    }
    public MainGUI(double dailyEarn){
        initComponents();
        //jLabel7.setText(String.valueOf(dailyEarn));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        UserNameSurname = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        digitalClockandDate2 = new com.callcenter.helper.DigitalClockandDate();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        homePanel2 = new com.callcenter.helper.HomePanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableProject = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableSubProject = new javax.swing.JTable();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        NewProjectName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        ProjectName = new javax.swing.JTextField();
        ProjectUpdate = new javax.swing.JButton();
        ProjectDelete = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        subProjectNameField = new javax.swing.JTextField();
        PriceField = new javax.swing.JTextField();
        CallTypeCombo = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        SubProjectInsertButton = new javax.swing.JButton();
        SubProjectUpdateButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        print2 = new com.callcenter.helper.Print();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        EmployeeName = new javax.swing.JTextField();
        EmployeeSurname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        EmployeeNickname = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        EmployeeEmail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        UpdateEmployee = new javax.swing.JButton();
        CancelEmployee = new javax.swing.JButton();
        EmployeePassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(230, 239, 247));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/callcenter/img/call-center.png"))); // NOI18N
        jLabel1.setText("Earn Calculator");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));
        jPanel1.add(UserNameSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/callcenter/img/call-center-2.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));
        jPanel1.add(digitalClockandDate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 65));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(590, 440));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(600, 440));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(homePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(homePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 70, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Home", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setMinimumSize(new java.awt.Dimension(590, 400));
        jPanel4.setPreferredSize(new java.awt.Dimension(590, 400));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TableProject.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Project Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableProject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableProjectMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableProject);
        if (TableProject.getColumnModel().getColumnCount() > 0) {
            TableProject.getColumnModel().getColumn(0).setMinWidth(0);
            TableProject.getColumnModel().getColumn(0).setPreferredWidth(0);
            TableProject.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 170));

        TableSubProject.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TableSubProject.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price", "Call Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableSubProject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableSubProjectMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableSubProject);
        if (TableSubProject.getColumnModel().getColumnCount() > 0) {
            TableSubProject.getColumnModel().getColumn(0).setMinWidth(30);
            TableSubProject.getColumnModel().getColumn(0).setPreferredWidth(30);
            TableSubProject.getColumnModel().getColumn(0).setMaxWidth(30);
            TableSubProject.getColumnModel().getColumn(2).setMinWidth(60);
            TableSubProject.getColumnModel().getColumn(2).setPreferredWidth(60);
            TableSubProject.getColumnModel().getColumn(2).setMaxWidth(60);
            TableSubProject.getColumnModel().getColumn(3).setMinWidth(100);
            TableSubProject.getColumnModel().getColumn(3).setPreferredWidth(100);
            TableSubProject.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 380, 170));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(234, 242, 250)));

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel17.setText("New Project Name");

        jButton1.setText("Add Project");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel18.setText("Select Project Name");

        ProjectUpdate.setText("Update");
        ProjectUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProjectUpdateActionPerformed(evt);
            }
        });

        ProjectDelete.setText("Delete");
        ProjectDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProjectDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(NewProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(ProjectUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ProjectDelete))
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(ProjectUpdate)
                    .addComponent(ProjectDelete))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Project Settings", jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Sub Project Name");

        jLabel19.setText("Price");

        jLabel20.setText("Call Type");

        CallTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Per Call", "Minute" }));

        jLabel21.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 51));
        jLabel21.setText("Sub project select");

        SubProjectInsertButton.setText("Add");
        SubProjectInsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubProjectInsertButtonActionPerformed(evt);
            }
        });

        SubProjectUpdateButton.setText("Update");
        SubProjectUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubProjectUpdateButtonActionPerformed(evt);
            }
        });

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subProjectNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(PriceField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CallTypeCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(SubProjectInsertButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SubProjectUpdateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(66, 66, 66))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SubProjectInsertButton)
                        .addComponent(SubProjectUpdateButton)
                        .addComponent(jButton4))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(subProjectNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(PriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(CallTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Sub Project Settings", jPanel9);

        jPanel4.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 580, 140));

        jTabbedPane1.addTab("Project", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(print2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(print2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 79, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Print", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel9.setText("Name");

        EmployeeName.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        EmployeeSurname.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel10.setText("Surname");

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel11.setText("Password");

        EmployeeNickname.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel12.setText("Nick Name");

        EmployeeEmail.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel13.setText("E-Mail");

        jLabel14.setText("Photo");

        jLabel15.setBackground(new java.awt.Color(234, 242, 250));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/callcenter/img/call-center-1.png"))); // NOI18N

        UpdateEmployee.setText("Update");
        UpdateEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateEmployeeActionPerformed(evt);
            }
        });

        CancelEmployee.setText("Cancel");
        CancelEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelEmployeeActionPerformed(evt);
            }
        });

        EmployeePassword.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EmployeeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(EmployeeNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EmployeeSurname, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(EmployeePassword))))
                .addGap(63, 63, 63)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(UpdateEmployee)
                        .addGap(18, 18, 18)
                        .addComponent(CancelEmployee))
                    .addComponent(jLabel14)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmployeeSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(EmployeePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmployeeNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmployeeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateEmployee)
                    .addComponent(CancelEmployee))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("User Setting", jPanel6);

        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 440));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 65, 600, 365));

        setSize(new java.awt.Dimension(599, 460));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateEmployeeActionPerformed
        try {
            this.employeeUpdate();
            this.employeeLoad();
            Helper.showMsg("update");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UpdateEmployeeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.employeeLoad();
        try {
            this.projectAddTable();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked

    }//GEN-LAST:event_jPanel6MouseClicked

    private void CancelEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelEmployeeActionPerformed
        this.employeeLoad();
    }//GEN-LAST:event_CancelEmployeeActionPerformed

    private void TableProjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableProjectMouseClicked
        int row = TableProject.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) TableProject.getModel();
        ProjectName.setText(model.getValueAt(row, 1).toString());
        idProject = (int) model.getValueAt(row, 0);
        jLabel21.setText(model.getValueAt(row, 1).toString());
        project = new Project(idProject, model.getValueAt(row, 1).toString());
        try {
            this.subProjectAddTable(project);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TableProjectMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            this.projectInsert();
            NewProjectName.setText("");
            Helper.showMsg("add");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ProjectDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProjectDeleteActionPerformed
        try {
            this.projectDelete();
            ProjectName.setText("");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ProjectDeleteActionPerformed

    private void ProjectUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProjectUpdateActionPerformed
        try {
            this.projectUpdate();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ProjectUpdateActionPerformed

    private void SubProjectUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubProjectUpdateButtonActionPerformed
        try {
            this.subProjectUpdate();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SubProjectUpdateButtonActionPerformed

    private void SubProjectInsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubProjectInsertButtonActionPerformed

        int subProjectId = 0;
        String subProjectName = subProjectNameField.getText();
        double price = Double.parseDouble(PriceField.getText());
        String callType = CallTypeCombo.getSelectedItem().toString();
        SubProject subProject = new SubProject(subProjectId, subProjectName, price, callType, project.getProjectId(), project.getProjectName());
        try {
            
            this.subProjectInsert(subProject);
            
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SubProjectInsertButtonActionPerformed

    private void TableSubProjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSubProjectMouseClicked
        int row = TableSubProject.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) TableSubProject.getModel();
        int subProjectId = Integer.parseInt(model.getValueAt(row, 0).toString());
        String subProjectName = model.getValueAt(row, 1).toString();
        double price = Double.parseDouble(model.getValueAt(row, 2).toString());
        String callType = model.getValueAt(row, 3).toString();
        subProjectNameField.setText(subProjectName);
        PriceField.setText(Double.toString(price));
        CallTypeCombo.setSelectedItem(callType);
        System.out.println(subProjectId);
        subProject = new SubProject(subProjectId, subProjectName, price, callType, project.getProjectId(), project.getProjectName()); 
    }//GEN-LAST:event_TableSubProjectMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            this.subprojectdelete();
            subProjectNameField.setText("");
            PriceField.setText("0");
            CallTypeCombo.setSelectedIndex(0);
            this.subProjectAddTable(project);
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }
//  ilk projenin alt projelerini listeler. tamamlanmadı!!

    private static void returnProject() throws ClassNotFoundException, SQLException {
        ProjectProcesses projectProcesses = new ProjectProcesses();
        Project project = projectProcesses.firstProject();
        if (project != null) {
            firstProject = project;
        }
    }

    private void employeeLoad() {
        EmployeeProcesses processes = new EmployeeProcesses();
        Employee employee = new Employee();
        try {
            employee = processes.getEmloyee(3);
            EmployeeName.setText(employee.getEmployeeName());
            EmployeeSurname.setText(employee.getEmployeeSurname());
            EmployeePassword.setText(employee.getPassword());
            EmployeeNickname.setText(employee.getEmployeeNickName());
            EmployeeEmail.setText(employee.getEmail());
            UserNameSurname.setText(employee.getEmployeeName() + " " + employee.getEmployeeSurname());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void employeeUpdate() throws ClassNotFoundException, SQLException {
        EmployeeProcesses processes = new EmployeeProcesses();
        Employee employee = new Employee(3,
                EmployeeName.getText(),
                EmployeeSurname.getText(),
                EmployeeNickname.getText(),
                EmployeeEmail.getText(),
                EmployeePassword.getText(),
                "");
        processes.updateEmployee(employee);
    }

    private void projectAddTable() throws ClassNotFoundException, SQLException {
        ProjectProcesses pjProcesses = new ProjectProcesses();
        int i = TableProject.getRowCount();

        projectModel = (DefaultTableModel) TableProject.getModel();
        for (int j = 0; j < i; j++) {
            projectModel.removeRow(0);
        }
        projectData = new Object[2];
        for (Project projectList : pjProcesses.getProjectList()) {
            projectData[0] = projectList.getProjectId();
            projectData[1] = projectList.getProjectName();
            projectModel.addRow(projectData);
            Project project = new Project(projectList.getProjectId(), projectList.getProjectName());
            this.subProjectAddTable(project);
        }

    }

    private void projectInsert() throws ClassNotFoundException, SQLException {
        ProjectProcesses pjproProcesses = new ProjectProcesses();
        boolean i = pjproProcesses.projectInsert(NewProjectName.getText());
        this.projectAddTable();
    }

    private void projectDelete() throws ClassNotFoundException, SQLException {
        ProjectProcesses pjproProcesses = new ProjectProcesses();
        pjproProcesses.projectDelete(idProject);
        this.projectAddTable();
    }

    private void projectUpdate() throws ClassNotFoundException, SQLException {
        ProjectProcesses pjproProcesses = new ProjectProcesses();
        Project project = new Project(idProject, ProjectName.getText());
        boolean i = pjproProcesses.projectUpdate(project);
        this.projectAddTable();
    }

    private void subProjectAddTable(Project project) throws ClassNotFoundException, SQLException {
        SubProjectProcesses subProjectProcesses = new SubProjectProcesses();
        int i = TableSubProject.getRowCount();

        subProjectModel = (DefaultTableModel) TableSubProject.getModel();
        for (int j = 0; j < i; j++) {
            subProjectModel.removeRow(0);
        }
        subProjectData = new Object[4];
        for (SubProject subProject : subProjectProcesses.getSubProjectList(project)) {
            subProjectData[0] = subProject.getSubProjectId();
            subProjectData[1] = subProject.getSubProjectName();
            subProjectData[2] = subProject.getPrice();
            subProjectData[3] = subProject.getCallType();
            subProjectModel.addRow(subProjectData);
        }
    }

    private void subProjectInsert(SubProject subProject) throws ClassNotFoundException, SQLException {
        SubProjectProcesses subProjectProcesses = new SubProjectProcesses();
        subProjectProcesses.subProjectInsert(subProject);
        this.subProjectAddTable(project);
    }
    
    private void subProjectUpdate() throws ClassNotFoundException, SQLException{
        SubProjectProcesses subProjectProcesses = new SubProjectProcesses();

        subProject.setSubProjectName(subProjectNameField.getText());
        subProject.setPrice(Double.parseDouble(PriceField.getText()));
        subProject.setCallType(CallTypeCombo.getSelectedItem().toString());
        
        boolean i = subProjectProcesses.subProjectUpdate(subProject);
        this.subProjectAddTable(subProject);
        
    }
    
    private void subprojectdelete() throws ClassNotFoundException, SQLException{
        SubProjectProcesses subProjectProcesses = new SubProjectProcesses();
        boolean i = subProjectProcesses.subProjectDelete(subProject);
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CallTypeCombo;
    private javax.swing.JButton CancelEmployee;
    private javax.swing.JTextField EmployeeEmail;
    private javax.swing.JTextField EmployeeName;
    private javax.swing.JTextField EmployeeNickname;
    private javax.swing.JPasswordField EmployeePassword;
    private javax.swing.JTextField EmployeeSurname;
    private javax.swing.JTextField NewProjectName;
    private javax.swing.JTextField PriceField;
    private javax.swing.JButton ProjectDelete;
    private javax.swing.JTextField ProjectName;
    private javax.swing.JButton ProjectUpdate;
    private javax.swing.JButton SubProjectInsertButton;
    private javax.swing.JButton SubProjectUpdateButton;
    private javax.swing.JTable TableProject;
    private javax.swing.JTable TableSubProject;
    private javax.swing.JButton UpdateEmployee;
    private javax.swing.JLabel UserNameSurname;
    private com.callcenter.helper.DigitalClockandDate digitalClockandDate2;
    private com.callcenter.helper.HomePanel homePanel2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private com.callcenter.helper.Print print2;
    private javax.swing.JTextField subProjectNameField;
    // End of variables declaration//GEN-END:variables
}
